# Generated by Django 2.2.1 on 2019-06-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_studentform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
